server:
  port: 8001
  
                     # mapper映射文件
    
spring:
   application:
    name: booko2ocloud-bookservice
 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: booko2ocloud-bookservice-8001
    prefer-ip-address: true     #访问路径可以显示IP地址    
info: 
  app.name: booko2o
  company.name: www.snbc.com
  build.artifactId: booko2ocloud-provider-bookservice-8001
  build.version: 0.0.1-SNAPSHOT